### ISSUE TITLE
Audio out of sync

### ISSUE THREAD

**Issue by Quppa** [tildearrow/kwin-lowlatency#100]
Software: KDE Plasma 5.20.1, Fedora 33, Qt 5.15.1, Kernel 5.8.15 (but was also happening under KDE Plasma 5.19/Fedora 32/Qt 5.14)
Hardware: Intel i7-2600K, AMD Radeon RX 570

When running the KWin-lowlatency fork, my system's audio seems to be out of sync by a very small but consistent amount. It seems to be application-independent - Firefox, VLC and mpv all behave the same, with or without hardware acceleration.

I recorded at 120 fps [this 59.94 fps video](https://www.quppa.net/temp/Audio%20Video%20Sync%20Lip%20Flap%20Project%205994.mp4) (from [PhotoJoseph.com](https://photojoseph.com/tips/2020/10/15/updated-downloadable-audiovideo-sync-tests-2398-24-25-2997-50-5994)) playing on my 60 Hz monitor to try and demonstrate the issue:
- [KWin](https://www.quppa.net/temp/kwin.mkv)
- [KWin-lowlatency](https://www.quppa.net/temp/kwin-lowlatency.mkv)

I zoomed in on the waveform display in Kdenlive and selected a similar point, just as a beep is happening. With KWin-lowlatency, the display shows +8, while with standard KWin it shows +4.

KWin:
![image](https://user-images.githubusercontent.com/2142963/97068459-88307980-1613-11eb-8593-d1db4f715b14.png)

KWin-lowlatency:
![image](https://user-images.githubusercontent.com/2142963/97068447-6a631480-1613-11eb-87ef-d389a482a2df.png)

**Comment by tildearrow** [comment]
This appears to be an audio latency issue, rather than a video latency one (positive values mean that the audio is too late).
Indeed, it appears kwin-lowlatency is doing its job right, by actually increasing the value from +4 to +8.

I just ran the test (using mpv, JACK (buffer size 128 at 44100Hz with 2 periods which means ~2.9-5.8ms of latency), the PulseAudio JACK sink and a monitor which has exactly 10ms of input lag according to displaylag.com.
Under this setup, I am getting -1 (this would perhaps be 0 if game mode is enabled on the monitor (disables extra processing to reduce latency)).

Are you using PulseAudio directly or JACK/ALSA/something? How are you outputting sound (HDMI or analog)?

**Comment by Quppa** [comment]
Hm, thanks, you're quite right about the audio being late - is KWin's extra latency actually helping me out here? :)

I'm using PulseAudio (13.99.2) with whatever defaults Fedora 33 provides. I'm outputting sound to a class 1 USB DAC.

I'll close this since it seems this isn't a KWin-lowlatency issue (I guess it just exposes the issue better).
