### ISSUE TITLE
Build error when applying patch to kwin 5.16.0

### ISSUE THREAD

**Issue by realnc** [tildearrow/kwin-lowlatency#18]
Building the kwin-lowlatency Plasma/5.16 branch  directly works fine. However, generating a patch with `patch.sh` and applying it to vanilla kwin 5.16.0, results in a build error:

<pre>
[  3%] Linking CXX shared library ../bin/libkwin4_effect_builtins.so
/usr/lib/gcc/x86_64-pc-linux-gnu/9.1.0/../../../../x86_64-pc-linux-gnu/bin/ld: CMakeFiles/kwin4_effect_builtins.dir/effect_builtins.cpp.o: in function `KWin::Effect* KWin::BuiltInEffects::createHelper<KWin::MousePosEffect>()':
effect_builtins.cpp:(.text._ZN4KWin14BuiltInEffects12createHelperINS_14MousePosEffectEEEPNS_6EffectEv[_ZN4KWin14BuiltInEffects12createHelperINS_14MousePosEffectEEEPNS_6EffectEv]+0x1a): undefined reference to `KWin::MousePosEffect::MousePosEffect()'
collect2: error: ld returned 1 exit status
</pre>

**Comment by realnc** [comment]
Removing `-x po -x CMakeLists.txt` from `patch.sh` fixes the issue. What's the reason for excluding these? Especially the cmake project files are vital for building.

**Comment by tildearrow** [comment]
... -x CMakeLists.txt? I can't believe it's still there...

The reason why po is excluded is because the official tar archives also add some language files which aren't present in the main repo... but CMakeLists still being excluded?

CMakeLists was excluded due to [this](https://github.com/tildearrow/kwin-lowlatency/issues/4#issuecomment-490697640), but the issue doesn't occur anymore so maybe I forgot to update the patch.sh file for 5.16... Will fix

**Comment by tildearrow** [comment]
I've fixed the patch generator. May you please confirm this is the case on your side?

**Comment by realnc** [comment]
Yep, it's fine now.
