### ISSUE TITLE
kwin-lowlatency still hangs on Mesa even with glFinish

### ISSUE THREAD

**Issue by tildearrow** [tildearrow/kwin-lowlatency#38]
After several hours of usage, the compositor may hang. This is hard to reproduce, as it requires me to get on my computer at 3-4pm so it reproduces at around 10pm-12am.

Let's hope the glFinish method isn't the culprit........

**Comment by Izaic** [comment]
I've noticed some hiccups like black boxes or lines around the cursor and the application windows being rendered as if a game was running (those white lines for the window resizing instead of proper compositing), but i think that's just kwin issues, and they don't happen for hours at a time.

No other issues other than that. I use a RX 590.

**Comment by MasterJubei** [comment]
I've been using kwin-lowlatency on Manjaro Deepin and left the system on days at a time without issue. Any bugs I've encountered are related to kwin, not kwin-lowlatency

**Comment by tildearrow** [comment]
Reproduced. Apparently Mesa bug.

Cannot delve further since I don't have debug symbols for Mesa, and I don't want to recompile the whole OS...

**Comment by qwertychouskie** [comment]
@tildearrow You should be able to just compile a debug copy of Mesa and use the `LIBGL_DRIVERS_PATH` and `LD_LIBRARY_PATH` env vars, recompiling the kernel and such should not be needed.

**Comment by tildearrow** [comment]
Did not occur any further.
