### ISSUE TITLE
[Feature] Re-implement Click-to-Close in Present Window Effect

### ISSUE THREAD

**Issue by r0skar** [tildearrow/kwin-lowlatency#5]
Hi! First of all: thanks for the great work you are doing. Although changing my nVidia card for an AMD card, helped a lot, I still see much better performance using your fork of kwin.

As you maybe are aware, there was a [very controversial decision](https://bugs.kde.org/show_bug.cgi?id=321190) to remove the click-to-close functionality from the Present Window effect. Luckily, it is very easy to [patch kwin to add the feature](https://aur.archlinux.org/cgit/aur.git/tree/presentwindows-close.patch?h=kwin-presentwindows-close) again.

I am currently applying a similar patch when building kwin and it works just fine. I was wondering whether you would consider adding this to your fork?

**Comment by tildearrow** [comment]
Done, in `pwclose` branch (9553f3e68790dabba9475433745d90f03c66d688).
Please test it out, and tell me if it works. If so, merging.

(replace `pkgrel=1` by `pkgrel=4` and `git checkout d0715021e48aada466d1001a49c5364d995bb85b` by `git checkout 9553f3e68790dabba9475433745d90f03c66d688` in the AUR package)

(post scriptum: I have not been aware of that debate since I only began using Linux (and KDE) as my main OS in 2015)

**Comment by r0skar** [comment]
Works great! Thanks a lot for the quick response. Looking forward to the patch landing in master.
p.s. I reopened the issue just in case you wanted to add something before merging it with master.

**Comment by tildearrow** [comment]
Merged. v5.15.5 to be released soon.
