### ISSUE TITLE
Manjaro installation instructions now out of date

### ISSUE THREAD

**Issue by Vykori** [tildearrow/kwin-lowlatency#65]
Manjaro just updated kwin and the other KDE things to 5.18.3-1, and my window manager was broken until I updated kwin-lowlatency to the latest (very fun to try on the desktop with no window manager!)

Hope I'm not doing anything improperly by submitting this issue, I'm new to the whole linux thing and rarely use Git

**Comment by ghost** [comment]
I can confirm that using the manual installation instructions after downloading the kwin-lowlatency 5.18.3 .zip or .tar.gz, extracting then cd into the extracted directory:

`$ mkdir build`
`$ cd build`
`$ cmake -DCMAKE_INSTALL_PREFIX=/usr -DCMAKE_INSTALL_LIBDIR=lib -DCMAKE_INSTALL_LIBEXECDIR=lib -DBUILD_TESTING=OFF ..`
`$ make`
`$ sudo make install`

Does in fact work on current Manjaro as of the most recent mass of updates. I am running it right now.

However, it does not appear to work from the AUR installation using the Manjaro software store either, hangs on "Waiting for another package manager to quit…” infinitely. Not really relevant as may be due to the distro itself not building it right, but just throwing that out there.

**Comment by tildearrow** [comment]
Thanks for pointing out!

@Furvy did you read the "a note about Pamac" section?
