### ISSUE TITLE
Can't build Plasma 5.19+ on Kubuntu

### ISSUE THREAD

**Issue by Odzinic** [tildearrow/kwin-lowlatency#90]
Hi,

More of a question than an issue. I've been having trouble building kwin-lowlatency for Kubuntu because the version of Qt that comes with 20.04 seems to be too old (5.12.8). The PPA for Ubuntu seems to have also been failing in building due to dependency issues the past few weeks. Is there another way this can be built? I haven't found a way to properly install the latest Qt on my system so I'm sure how to go about doing this. Sorry if this is a newbie question. Thanks.

**Comment by maxiberta** [comment]
Hi! Author of the Kubuntu PPA here. Afaik, Plasma 5.19 requires Qt 5.14+, so unfortunately I don't think kwin can be built on Ubuntu as long as a newer Qt is not available (if ever, being an LTS release - or maybe 20.04.1? I don't really know). Alternatively, there's the kde neon PPA which includes Qt 5.14.2, but it's not possible to provide a "kwin-lowlatency for Neon" PPA because Launchpad requires all dependencies hosted on itself and neon repo is hosted somewhere else, so you need to build it yourself.

Please correct me if I'm wrong. Happy to update the PPA.

**Comment by maxiberta** [comment]
Check [Kubuntu's backports policy for LTS releases](https://community.kde.org/Kubuntu/Policies#Long_Term_Support_.28LTS.29):

> release backports are made available through the Kubuntu PPA for as long as supported by the native LTS software stack (including Qt version)

**Comment by Odzinic** [comment]
Hi @maxiberta. Thanks for the insight. Guess I'll have to wait until Kubuntu 20.10. Also thanks for maintaining the PPA!
